import React from 'react';
import { Link } from 'react-router-dom';
import { Clock, HardDrive, CheckSquare, AlertTriangle, Zap, Bot, ArrowRight, Code2 } from 'lucide-react';
import { SUPPORTED_LANGUAGES } from '../utils/languages';

export const HomePage: React.FC = () => {
  const features = [
    { title: 'Time Complexity Analysis', description: 'Estimates asymptotic time bounds from loops, nesting, recursion, and common operations without executing source code.', icon: Clock, badge: 'Performance' },
    { title: 'Space Complexity Analysis', description: 'Estimates auxiliary memory from collections, allocations, and recursive call-stack growth.', icon: HardDrive, badge: 'Memory' },
    { title: 'Code Quality Analysis', description: 'Reports structural metrics such as cyclomatic complexity, function count, variables, branches, and nesting.', icon: CheckSquare, badge: 'Diagnostics' },
    { title: 'Code Smell Detection', description: 'Flags deep nesting, high branching, oversized source files, and other maintainability signals.', icon: AlertTriangle, badge: 'Refactoring' },
    { title: 'Optimization Suggestions', description: 'Provides conditional improvement ideas based on the detected source structure rather than blindly rewriting algorithms.', icon: Zap, badge: 'Efficiency' },
    { title: 'Gemini-Powered Explanations', description: 'Uses Gemini on the server side to review static findings and turn them into contextual explanations and suggestions.', icon: Bot, badge: 'AI' },
  ];
  const languagesList = Object.values(SUPPORTED_LANGUAGES);
  return <div className="flex-1 flex flex-col">
    <section className="border-b border-zinc-200 dark:border-zinc-800 bg-white dark:bg-zinc-900/60 py-16 sm:py-20"><div className="max-w-5xl mx-auto px-4 sm:px-6 lg:px-8 text-center">
      <div className="inline-flex items-center gap-2 px-3 py-1 rounded-full bg-emerald-50 dark:bg-emerald-950/30 border border-emerald-200 dark:border-emerald-800 text-xs font-medium text-emerald-700 dark:text-emerald-300 mb-6"><span className="w-2 h-2 rounded-full bg-emerald-500 animate-pulse" />Analysis Engine Active</div>
      <h1 className="text-3xl sm:text-5xl font-bold tracking-tight text-zinc-900 dark:text-zinc-50 max-w-3xl mx-auto leading-tight">AI-Powered Code Complexity Analyzer</h1>
      <p className="mt-6 text-base sm:text-lg text-zinc-600 dark:text-zinc-300 max-w-2xl mx-auto leading-relaxed">Understand time and space complexity, inspect code quality, spot structural smells, and receive Gemini-powered explanations without executing your code.</p>
      <div className="mt-8 flex flex-col sm:flex-row items-center justify-center gap-4"><Link to="/analyzer" id="hero-start-analyzing-btn" className="w-full sm:w-auto inline-flex items-center justify-center gap-2 px-6 py-3 rounded-lg bg-zinc-900 dark:bg-emerald-600 text-white font-medium text-sm shadow-sm"><span>Start Analyzing</span><ArrowRight className="w-4 h-4" /></Link></div>
      <div className="mt-12 pt-8 border-t border-zinc-200 dark:border-zinc-800/80 grid grid-cols-2 md:grid-cols-4 gap-4 text-left">
        <div className="p-3 rounded-lg bg-zinc-50 dark:bg-zinc-800/40 border border-zinc-200/60 dark:border-zinc-800"><div className="text-xs text-zinc-500">Analysis Engine</div><div className="text-sm font-semibold text-zinc-800 dark:text-zinc-200 mt-0.5">Static Source Analysis</div></div>
        <div className="p-3 rounded-lg bg-zinc-50 dark:bg-zinc-800/40 border border-zinc-200/60 dark:border-zinc-800"><div className="text-xs text-zinc-500">AI Reasoning</div><div className="text-sm font-semibold text-zinc-800 dark:text-zinc-200 mt-0.5">Gemini API</div></div>
        <div className="p-3 rounded-lg bg-zinc-50 dark:bg-zinc-800/40 border border-zinc-200/60 dark:border-zinc-800"><div className="text-xs text-zinc-500">Editor</div><div className="text-sm font-semibold text-zinc-800 dark:text-zinc-200 mt-0.5">Monaco Editor</div></div>
        <div className="p-3 rounded-lg bg-zinc-50 dark:bg-zinc-800/40 border border-zinc-200/60 dark:border-zinc-800"><div className="text-xs text-zinc-500">Execution</div><div className="text-sm font-semibold text-zinc-800 dark:text-zinc-200 mt-0.5">Never Executed</div></div>
      </div>
    </div></section>
    <section className="py-16 bg-zinc-50 dark:bg-zinc-950"><div className="max-w-6xl mx-auto px-4 sm:px-6 lg:px-8"><div className="text-center max-w-2xl mx-auto mb-12"><h2 className="text-2xl sm:text-3xl font-bold tracking-tight text-zinc-900 dark:text-zinc-100">Comprehensive Code Intelligence</h2><p className="mt-3 text-sm sm:text-base text-zinc-600 dark:text-zinc-400">Deterministic source inspection provides measurable structure; Gemini adds contextual reasoning on top.</p></div><div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6">{features.map((feature, idx) => { const Icon = feature.icon; return <div key={idx} id={`feature-card-${idx}`} className="p-6 rounded-xl bg-white dark:bg-zinc-900 border border-zinc-200 dark:border-zinc-800 flex flex-col"><div className="flex items-center justify-between mb-4"><div className="w-10 h-10 rounded-lg bg-zinc-100 dark:bg-zinc-800 flex items-center justify-center"><Icon className="w-5 h-5 text-emerald-600 dark:text-emerald-400" /></div><span className="text-[11px] font-mono uppercase bg-zinc-100 dark:bg-zinc-800 px-2 py-0.5 rounded">{feature.badge}</span></div><h3 className="text-base font-semibold text-zinc-900 dark:text-zinc-100 mb-2">{feature.title}</h3><p className="text-sm text-zinc-600 dark:text-zinc-400 leading-relaxed">{feature.description}</p></div>; })}</div></div></section>
    <section className="py-16 border-t border-zinc-200 dark:border-zinc-800 bg-white dark:bg-zinc-900/40"><div className="max-w-5xl mx-auto px-4 sm:px-6 lg:px-8"><h2 className="text-xl sm:text-2xl font-bold tracking-tight text-zinc-900 dark:text-zinc-100">Supported Languages</h2><p className="mt-1 text-sm text-zinc-600 dark:text-zinc-400">Java, C, C++, and Python are currently supported.</p><div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-4 gap-4 mt-8">{languagesList.map((lang) => <div key={lang.id} className="p-5 rounded-lg border border-zinc-200 dark:border-zinc-800 bg-zinc-50 dark:bg-zinc-900"><div className="flex items-center justify-between mb-3"><span className="font-semibold text-base text-zinc-900 dark:text-zinc-100">{lang.name}</span><span className="text-xs font-mono px-2 py-0.5 rounded bg-zinc-200 dark:bg-zinc-800">{lang.extensions.join(', ')}</span></div><p className="text-xs text-zinc-500 dark:text-zinc-400">{lang.description}</p></div>)}</div><div className="mt-12 p-6 rounded-xl border border-zinc-200 dark:border-zinc-800 bg-zinc-50 dark:bg-zinc-800/50 flex flex-col sm:flex-row items-center justify-between gap-4"><div><h3 className="font-semibold text-zinc-900 dark:text-zinc-100">Ready to inspect source code?</h3><p className="text-xs sm:text-sm text-zinc-600 dark:text-zinc-400 mt-0.5">Open the Monaco workspace and analyze a snippet, method, or source file.</p></div><Link to="/analyzer" className="inline-flex items-center gap-2 px-4 py-2 rounded-lg bg-zinc-900 dark:bg-emerald-600 text-white text-xs sm:text-sm font-medium"><Code2 className="w-4 h-4" />Open Analyzer</Link></div></div></section>
  </div>;
};
